version: "3"
services: 
  sql_db:
    image: mysql:latest
    container_name: my_mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_database
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    volumes:
      - ./mysql_data:/var/lib/mysql
  #mosquitto:
  #  image: eclipse-mosquitto
  #  container_name: mosquitto
  #  ports:
  #    - "1883:1883"
  #    - "9001:9001"
  #  volumes:
  #    - "mosquitto-data:/mosquitto"
  node-red:
    image: nodered/node-red
    container_name: node-red
    ports:
      - "1880:1880"
    volumes:
      - "node-red-data:/data"
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"        
    volumes:
      - "influxdb-data:/var/lib/influxdb"
  grafana:
    image: benayyad12/grafana-nb-iot:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "grafana-data:/var/lib/grafana"
volumes:
  influxdb-data:
  grafana-data:        
  node-red-data:
  mosquitto-data:
